#include<stdio.h>
int main(){
  printf("\tuse of signed char modifier\n ");
	signed char k ='1';
	printf("value of k=%c\n",k);
	printf("memory of k=%ld bytes\n",sizeof(k));
	printf("\tuse of short int\n ");
	short int a= -32768;
	printf("value of a=%d\n",a);
	printf("memory of a=%ld bytes\n",sizeof(a));
	printf("\tuse of unsigned short int\n ");
	unsigned short int b= 65535;
	printf("value of b=%d\n",b);
	printf("memory of b=%ld bytes\n",sizeof(b));
	printf("\tuse of int \n");
	int c= -2147483648;
	printf("value of c=%d\n",a);
	printf("memory of c=%ld bytes\n",sizeof(c));
	printf("\tuse of unsigned int modifier\n ");
	unsigned int d= 4294967295;
	printf("value of d=%u\n",a);
	printf("memory of d=%ld bytes\n",sizeof(d));
	printf("\tuse of float modifier\n ");
	float  e= 32.89768;
	printf("value of e=%f\n",e);
	printf("memory of e=%ld bytes\n",sizeof(e));
	printf("\tuse of iong int modifier\n ");
	long int f= -2147483648;
	printf("value of f=%ld\n",f);
	printf("memory of f=%ld bytes\n",sizeof(f));
	printf("\tuse of unsigned long int modifier \n");
	unsigned long int g= 4294967295;
	printf("value of g=%lu\n",g);
	printf("memory of g=%ld bytes\n",sizeof(g));
	printf("\tuse of long long modifier \n");
	long long h= -9223372036854775;
	printf("value of h=%lld\n",h);
	printf("memory of h=%ld bytes\n",sizeof(h));
	printf("\tuse of unsigned long long modifier \n");
	unsigned long long i= 18345869574859624;
	printf("value of i=%llu\n",i);
	printf("memory of i=%ld bytes\n",sizeof(i));
	return 0;
}
